# Generated by Django 3.1.5 on 2021-02-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0141_update_product_ts_vector"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE product_product ADD COLUMN IF NOT EXISTS is_original_name BOOLEAN DEFAULT TRUE; 
            """
        ),
        migrations.RunSQL(
            """
            ALTER TABLE product_product ADD COLUMN IF NOT EXISTS is_original_description BOOLEAN DEFAULT TRUE;
            """
        ),
        migrations.RunSQL(
            """
            CREATE FUNCTION value_change_control_function() RETURNS trigger AS $$
            begin
                IF NEW.name <> OLD.name THEN
                    NEW.is_original_name = false;
                ELSIF NEW.description <> OLD.description THEN
                    NEW.is_original_description = false;
                END IF;

                RETURN NEW;
            end
            $$ LANGUAGE plpgsql;
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER value_change_control BEFORE UPDATE
            ON product_product FOR EACH ROW EXECUTE PROCEDURE
            value_change_control_function()
            """
        ),
    ]
